import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  headerContent: {
    padding: 30,
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
    flex: 1,
    marginTop: 63,
  },
  groupButtons: {
    flex: 1,
    flexDirection: "row",
    gap: 10,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 63,
    borderWidth: 2,
    borderColor: "white",
    marginBottom: 10,
    margin: 2,
  },
  name: {
    fontSize: 22,
    color: "black",
    fontWeight: "600",
    fontFamily: "Helvetica",
  },
  headtText: {
    fontFamily: "Helvetica",
    color: "grey",
    fontWeight: "600",
    marginLeft: 20,
    marginTop: 10,
  },
  SubjectText: {
    color: "black",
    fontSize: 16,
    fontFamily: "Helvetica",
    marginLeft: 20,
    marginTop: 10,
  },
  userInfo: {
    fontSize: 20,
    color: "white",
    fontWeight: "600",
  },
  btn: {
    marginTop: 20,
    backgroundColor: "#3B525F",
    borderRadius: 10,
    width: "40%",
    height: 50,
    alignItems: "center",
    padding: 6,
    elevation: 30,
  },
  body: {
    backgroundColor: "white",
    alignItems: "center",
    height: 500,
  },
  text: {
    color: "white",
    margin: 10,
  },
  RectangleShapeView: {
    marginTop: 20,
    width: "90%",
    height: 80,
    backgroundColor: "white",
    color: "black",
    borderRadius: 10,
    borderColor: "black",
    borderWidth: 1,
    elevation: 3,
  },
  Flex: {
    flex: 1,
    flexDirection: "row",
  },
});
